// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.7.0 (commit 02c67d121b0d08478eaf3512f479e7a326d39940).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { CancelPvpMatch } from "./cancel_pvp_match_reducer.ts";
export { CancelPvpMatch };
import { CompletePvpMatch } from "./complete_pvp_match_reducer.ts";
export { CompletePvpMatch };
import { CreatePvpMatch } from "./create_pvp_match_reducer.ts";
export { CreatePvpMatch };
import { CreatePvpMatchWithCode } from "./create_pvp_match_with_code_reducer.ts";
export { CreatePvpMatchWithCode };
import { JoinMatchQueue } from "./join_match_queue_reducer.ts";
export { JoinMatchQueue };
import { JoinPvpMatch } from "./join_pvp_match_reducer.ts";
export { JoinPvpMatch };
import { JoinPvpMatchByCode } from "./join_pvp_match_by_code_reducer.ts";
export { JoinPvpMatchByCode };
import { LeaveMatchQueue } from "./leave_match_queue_reducer.ts";
export { LeaveMatchQueue };
import { RebuildLeaderboard } from "./rebuild_leaderboard_reducer.ts";
export { RebuildLeaderboard };
import { RecordContinuePayment } from "./record_continue_payment_reducer.ts";
export { RecordContinuePayment };
import { RegisterPlayer } from "./register_player_reducer.ts";
export { RegisterPlayer };
import { SetPlayerMusic } from "./set_player_music_reducer.ts";
export { SetPlayerMusic };
import { StartSingleRun } from "./start_single_run_reducer.ts";
export { StartSingleRun };
import { UpdatePvpBoard } from "./update_pvp_board_reducer.ts";
export { UpdatePvpBoard };
import { UpdateSingleRun } from "./update_single_run_reducer.ts";
export { UpdateSingleRun };

// Import and reexport all table handle types
import { GameRunsTableHandle } from "./game_runs_table.ts";
export { GameRunsTableHandle };
import { MatchQueueTableHandle } from "./match_queue_table.ts";
export { MatchQueueTableHandle };
import { PaymentRecordsTableHandle } from "./payment_records_table.ts";
export { PaymentRecordsTableHandle };
import { PlayersTableHandle } from "./players_table.ts";
export { PlayersTableHandle };
import { PvpLeaderboardTableHandle } from "./pvp_leaderboard_table.ts";
export { PvpLeaderboardTableHandle };
import { PvpMatchesTableHandle } from "./pvp_matches_table.ts";
export { PvpMatchesTableHandle };
import { SpLeaderboardTableHandle } from "./sp_leaderboard_table.ts";
export { SpLeaderboardTableHandle };

// Import and reexport all types
import { GameRun } from "./game_run_type.ts";
export { GameRun };
import { MatchQueue } from "./match_queue_type.ts";
export { MatchQueue };
import { MatchStatus } from "./match_status_type.ts";
export { MatchStatus };
import { MatchType } from "./match_type_type.ts";
export { MatchType };
import { PaymentRecord } from "./payment_record_type.ts";
export { PaymentRecord };
import { Player } from "./player_type.ts";
export { Player };
import { PvpLeaderboard } from "./pvp_leaderboard_type.ts";
export { PvpLeaderboard };
import { PvpMatch } from "./pvp_match_type.ts";
export { PvpMatch };
import { SpLeaderboardEntry } from "./sp_leaderboard_entry_type.ts";
export { SpLeaderboardEntry };

const REMOTE_MODULE = {
  tables: {
    game_runs: {
      tableName: "game_runs" as const,
      rowType: GameRun.getTypeScriptAlgebraicType(),
      primaryKey: "runId",
      primaryKeyInfo: {
        colName: "runId",
        colType: (GameRun.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    match_queue: {
      tableName: "match_queue" as const,
      rowType: MatchQueue.getTypeScriptAlgebraicType(),
      primaryKey: "queueId",
      primaryKeyInfo: {
        colName: "queueId",
        colType: (MatchQueue.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    payment_records: {
      tableName: "payment_records" as const,
      rowType: PaymentRecord.getTypeScriptAlgebraicType(),
      primaryKey: "paymentId",
      primaryKeyInfo: {
        colName: "paymentId",
        colType: (PaymentRecord.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    players: {
      tableName: "players" as const,
      rowType: Player.getTypeScriptAlgebraicType(),
      primaryKey: "wallet",
      primaryKeyInfo: {
        colName: "wallet",
        colType: (Player.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    pvp_leaderboard: {
      tableName: "pvp_leaderboard" as const,
      rowType: PvpLeaderboard.getTypeScriptAlgebraicType(),
      primaryKey: "wallet",
      primaryKeyInfo: {
        colName: "wallet",
        colType: (PvpLeaderboard.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    pvp_matches: {
      tableName: "pvp_matches" as const,
      rowType: PvpMatch.getTypeScriptAlgebraicType(),
      primaryKey: "matchId",
      primaryKeyInfo: {
        colName: "matchId",
        colType: (PvpMatch.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    sp_leaderboard: {
      tableName: "sp_leaderboard" as const,
      rowType: SpLeaderboardEntry.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (SpLeaderboardEntry.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    cancel_pvp_match: {
      reducerName: "cancel_pvp_match",
      argsType: CancelPvpMatch.getTypeScriptAlgebraicType(),
    },
    complete_pvp_match: {
      reducerName: "complete_pvp_match",
      argsType: CompletePvpMatch.getTypeScriptAlgebraicType(),
    },
    create_pvp_match: {
      reducerName: "create_pvp_match",
      argsType: CreatePvpMatch.getTypeScriptAlgebraicType(),
    },
    create_pvp_match_with_code: {
      reducerName: "create_pvp_match_with_code",
      argsType: CreatePvpMatchWithCode.getTypeScriptAlgebraicType(),
    },
    join_match_queue: {
      reducerName: "join_match_queue",
      argsType: JoinMatchQueue.getTypeScriptAlgebraicType(),
    },
    join_pvp_match: {
      reducerName: "join_pvp_match",
      argsType: JoinPvpMatch.getTypeScriptAlgebraicType(),
    },
    join_pvp_match_by_code: {
      reducerName: "join_pvp_match_by_code",
      argsType: JoinPvpMatchByCode.getTypeScriptAlgebraicType(),
    },
    leave_match_queue: {
      reducerName: "leave_match_queue",
      argsType: LeaveMatchQueue.getTypeScriptAlgebraicType(),
    },
    rebuild_leaderboard: {
      reducerName: "rebuild_leaderboard",
      argsType: RebuildLeaderboard.getTypeScriptAlgebraicType(),
    },
    record_continue_payment: {
      reducerName: "record_continue_payment",
      argsType: RecordContinuePayment.getTypeScriptAlgebraicType(),
    },
    register_player: {
      reducerName: "register_player",
      argsType: RegisterPlayer.getTypeScriptAlgebraicType(),
    },
    set_player_music: {
      reducerName: "set_player_music",
      argsType: SetPlayerMusic.getTypeScriptAlgebraicType(),
    },
    start_single_run: {
      reducerName: "start_single_run",
      argsType: StartSingleRun.getTypeScriptAlgebraicType(),
    },
    update_pvp_board: {
      reducerName: "update_pvp_board",
      argsType: UpdatePvpBoard.getTypeScriptAlgebraicType(),
    },
    update_single_run: {
      reducerName: "update_single_run",
      argsType: UpdateSingleRun.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.7.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "CancelPvpMatch", args: CancelPvpMatch }
| { name: "CompletePvpMatch", args: CompletePvpMatch }
| { name: "CreatePvpMatch", args: CreatePvpMatch }
| { name: "CreatePvpMatchWithCode", args: CreatePvpMatchWithCode }
| { name: "JoinMatchQueue", args: JoinMatchQueue }
| { name: "JoinPvpMatch", args: JoinPvpMatch }
| { name: "JoinPvpMatchByCode", args: JoinPvpMatchByCode }
| { name: "LeaveMatchQueue", args: LeaveMatchQueue }
| { name: "RebuildLeaderboard", args: RebuildLeaderboard }
| { name: "RecordContinuePayment", args: RecordContinuePayment }
| { name: "RegisterPlayer", args: RegisterPlayer }
| { name: "SetPlayerMusic", args: SetPlayerMusic }
| { name: "StartSingleRun", args: StartSingleRun }
| { name: "UpdatePvpBoard", args: UpdatePvpBoard }
| { name: "UpdateSingleRun", args: UpdateSingleRun }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  cancelPvpMatch(matchId: bigint) {
    const __args = { matchId };
    let __writer = new __BinaryWriter(1024);
    CancelPvpMatch.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("cancel_pvp_match", __argsBuffer, this.setCallReducerFlags.cancelPvpMatchFlags);
  }

  onCancelPvpMatch(callback: (ctx: ReducerEventContext, matchId: bigint) => void) {
    this.connection.onReducer("cancel_pvp_match", callback);
  }

  removeOnCancelPvpMatch(callback: (ctx: ReducerEventContext, matchId: bigint) => void) {
    this.connection.offReducer("cancel_pvp_match", callback);
  }

  completePvpMatch(matchId: bigint, winnerWallet: string) {
    const __args = { matchId, winnerWallet };
    let __writer = new __BinaryWriter(1024);
    CompletePvpMatch.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("complete_pvp_match", __argsBuffer, this.setCallReducerFlags.completePvpMatchFlags);
  }

  onCompletePvpMatch(callback: (ctx: ReducerEventContext, matchId: bigint, winnerWallet: string) => void) {
    this.connection.onReducer("complete_pvp_match", callback);
  }

  removeOnCompletePvpMatch(callback: (ctx: ReducerEventContext, matchId: bigint, winnerWallet: string) => void) {
    this.connection.offReducer("complete_pvp_match", callback);
  }

  createPvpMatch(wallet: string, matchType: MatchType) {
    const __args = { wallet, matchType };
    let __writer = new __BinaryWriter(1024);
    CreatePvpMatch.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_pvp_match", __argsBuffer, this.setCallReducerFlags.createPvpMatchFlags);
  }

  onCreatePvpMatch(callback: (ctx: ReducerEventContext, wallet: string, matchType: MatchType) => void) {
    this.connection.onReducer("create_pvp_match", callback);
  }

  removeOnCreatePvpMatch(callback: (ctx: ReducerEventContext, wallet: string, matchType: MatchType) => void) {
    this.connection.offReducer("create_pvp_match", callback);
  }

  createPvpMatchWithCode(wallet: string, matchType: MatchType, joinCode: string) {
    const __args = { wallet, matchType, joinCode };
    let __writer = new __BinaryWriter(1024);
    CreatePvpMatchWithCode.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_pvp_match_with_code", __argsBuffer, this.setCallReducerFlags.createPvpMatchWithCodeFlags);
  }

  onCreatePvpMatchWithCode(callback: (ctx: ReducerEventContext, wallet: string, matchType: MatchType, joinCode: string) => void) {
    this.connection.onReducer("create_pvp_match_with_code", callback);
  }

  removeOnCreatePvpMatchWithCode(callback: (ctx: ReducerEventContext, wallet: string, matchType: MatchType, joinCode: string) => void) {
    this.connection.offReducer("create_pvp_match_with_code", callback);
  }

  joinMatchQueue(wallet: string, matchType: MatchType) {
    const __args = { wallet, matchType };
    let __writer = new __BinaryWriter(1024);
    JoinMatchQueue.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("join_match_queue", __argsBuffer, this.setCallReducerFlags.joinMatchQueueFlags);
  }

  onJoinMatchQueue(callback: (ctx: ReducerEventContext, wallet: string, matchType: MatchType) => void) {
    this.connection.onReducer("join_match_queue", callback);
  }

  removeOnJoinMatchQueue(callback: (ctx: ReducerEventContext, wallet: string, matchType: MatchType) => void) {
    this.connection.offReducer("join_match_queue", callback);
  }

  joinPvpMatch(wallet: string, matchId: bigint) {
    const __args = { wallet, matchId };
    let __writer = new __BinaryWriter(1024);
    JoinPvpMatch.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("join_pvp_match", __argsBuffer, this.setCallReducerFlags.joinPvpMatchFlags);
  }

  onJoinPvpMatch(callback: (ctx: ReducerEventContext, wallet: string, matchId: bigint) => void) {
    this.connection.onReducer("join_pvp_match", callback);
  }

  removeOnJoinPvpMatch(callback: (ctx: ReducerEventContext, wallet: string, matchId: bigint) => void) {
    this.connection.offReducer("join_pvp_match", callback);
  }

  joinPvpMatchByCode(wallet: string, joinCode: string) {
    const __args = { wallet, joinCode };
    let __writer = new __BinaryWriter(1024);
    JoinPvpMatchByCode.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("join_pvp_match_by_code", __argsBuffer, this.setCallReducerFlags.joinPvpMatchByCodeFlags);
  }

  onJoinPvpMatchByCode(callback: (ctx: ReducerEventContext, wallet: string, joinCode: string) => void) {
    this.connection.onReducer("join_pvp_match_by_code", callback);
  }

  removeOnJoinPvpMatchByCode(callback: (ctx: ReducerEventContext, wallet: string, joinCode: string) => void) {
    this.connection.offReducer("join_pvp_match_by_code", callback);
  }

  leaveMatchQueue(wallet: string) {
    const __args = { wallet };
    let __writer = new __BinaryWriter(1024);
    LeaveMatchQueue.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("leave_match_queue", __argsBuffer, this.setCallReducerFlags.leaveMatchQueueFlags);
  }

  onLeaveMatchQueue(callback: (ctx: ReducerEventContext, wallet: string) => void) {
    this.connection.onReducer("leave_match_queue", callback);
  }

  removeOnLeaveMatchQueue(callback: (ctx: ReducerEventContext, wallet: string) => void) {
    this.connection.offReducer("leave_match_queue", callback);
  }

  rebuildLeaderboard() {
    this.connection.callReducer("rebuild_leaderboard", new Uint8Array(0), this.setCallReducerFlags.rebuildLeaderboardFlags);
  }

  onRebuildLeaderboard(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("rebuild_leaderboard", callback);
  }

  removeOnRebuildLeaderboard(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("rebuild_leaderboard", callback);
  }

  recordContinuePayment(wallet: string, runId: bigint, amountCents: bigint, txHash: string) {
    const __args = { wallet, runId, amountCents, txHash };
    let __writer = new __BinaryWriter(1024);
    RecordContinuePayment.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("record_continue_payment", __argsBuffer, this.setCallReducerFlags.recordContinuePaymentFlags);
  }

  onRecordContinuePayment(callback: (ctx: ReducerEventContext, wallet: string, runId: bigint, amountCents: bigint, txHash: string) => void) {
    this.connection.onReducer("record_continue_payment", callback);
  }

  removeOnRecordContinuePayment(callback: (ctx: ReducerEventContext, wallet: string, runId: bigint, amountCents: bigint, txHash: string) => void) {
    this.connection.offReducer("record_continue_payment", callback);
  }

  registerPlayer(wallet: string) {
    const __args = { wallet };
    let __writer = new __BinaryWriter(1024);
    RegisterPlayer.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("register_player", __argsBuffer, this.setCallReducerFlags.registerPlayerFlags);
  }

  onRegisterPlayer(callback: (ctx: ReducerEventContext, wallet: string) => void) {
    this.connection.onReducer("register_player", callback);
  }

  removeOnRegisterPlayer(callback: (ctx: ReducerEventContext, wallet: string) => void) {
    this.connection.offReducer("register_player", callback);
  }

  setPlayerMusic(wallet: string, musicOn: boolean) {
    const __args = { wallet, musicOn };
    let __writer = new __BinaryWriter(1024);
    SetPlayerMusic.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("set_player_music", __argsBuffer, this.setCallReducerFlags.setPlayerMusicFlags);
  }

  onSetPlayerMusic(callback: (ctx: ReducerEventContext, wallet: string, musicOn: boolean) => void) {
    this.connection.onReducer("set_player_music", callback);
  }

  removeOnSetPlayerMusic(callback: (ctx: ReducerEventContext, wallet: string, musicOn: boolean) => void) {
    this.connection.offReducer("set_player_music", callback);
  }

  startSingleRun(wallet: string, initialBoard: string, level: number) {
    const __args = { wallet, initialBoard, level };
    let __writer = new __BinaryWriter(1024);
    StartSingleRun.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("start_single_run", __argsBuffer, this.setCallReducerFlags.startSingleRunFlags);
  }

  onStartSingleRun(callback: (ctx: ReducerEventContext, wallet: string, initialBoard: string, level: number) => void) {
    this.connection.onReducer("start_single_run", callback);
  }

  removeOnStartSingleRun(callback: (ctx: ReducerEventContext, wallet: string, initialBoard: string, level: number) => void) {
    this.connection.offReducer("start_single_run", callback);
  }

  updatePvpBoard(matchId: bigint, wallet: string, boardState: string, score: bigint) {
    const __args = { matchId, wallet, boardState, score };
    let __writer = new __BinaryWriter(1024);
    UpdatePvpBoard.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_pvp_board", __argsBuffer, this.setCallReducerFlags.updatePvpBoardFlags);
  }

  onUpdatePvpBoard(callback: (ctx: ReducerEventContext, matchId: bigint, wallet: string, boardState: string, score: bigint) => void) {
    this.connection.onReducer("update_pvp_board", callback);
  }

  removeOnUpdatePvpBoard(callback: (ctx: ReducerEventContext, matchId: bigint, wallet: string, boardState: string, score: bigint) => void) {
    this.connection.offReducer("update_pvp_board", callback);
  }

  updateSingleRun(runId: bigint, score: bigint, linesCleared: number, levelReached: number, boardState: string, active: boolean, won: boolean) {
    const __args = { runId, score, linesCleared, levelReached, boardState, active, won };
    let __writer = new __BinaryWriter(1024);
    UpdateSingleRun.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_single_run", __argsBuffer, this.setCallReducerFlags.updateSingleRunFlags);
  }

  onUpdateSingleRun(callback: (ctx: ReducerEventContext, runId: bigint, score: bigint, linesCleared: number, levelReached: number, boardState: string, active: boolean, won: boolean) => void) {
    this.connection.onReducer("update_single_run", callback);
  }

  removeOnUpdateSingleRun(callback: (ctx: ReducerEventContext, runId: bigint, score: bigint, linesCleared: number, levelReached: number, boardState: string, active: boolean, won: boolean) => void) {
    this.connection.offReducer("update_single_run", callback);
  }

}

export class SetReducerFlags {
  cancelPvpMatchFlags: __CallReducerFlags = 'FullUpdate';
  cancelPvpMatch(flags: __CallReducerFlags) {
    this.cancelPvpMatchFlags = flags;
  }

  completePvpMatchFlags: __CallReducerFlags = 'FullUpdate';
  completePvpMatch(flags: __CallReducerFlags) {
    this.completePvpMatchFlags = flags;
  }

  createPvpMatchFlags: __CallReducerFlags = 'FullUpdate';
  createPvpMatch(flags: __CallReducerFlags) {
    this.createPvpMatchFlags = flags;
  }

  createPvpMatchWithCodeFlags: __CallReducerFlags = 'FullUpdate';
  createPvpMatchWithCode(flags: __CallReducerFlags) {
    this.createPvpMatchWithCodeFlags = flags;
  }

  joinMatchQueueFlags: __CallReducerFlags = 'FullUpdate';
  joinMatchQueue(flags: __CallReducerFlags) {
    this.joinMatchQueueFlags = flags;
  }

  joinPvpMatchFlags: __CallReducerFlags = 'FullUpdate';
  joinPvpMatch(flags: __CallReducerFlags) {
    this.joinPvpMatchFlags = flags;
  }

  joinPvpMatchByCodeFlags: __CallReducerFlags = 'FullUpdate';
  joinPvpMatchByCode(flags: __CallReducerFlags) {
    this.joinPvpMatchByCodeFlags = flags;
  }

  leaveMatchQueueFlags: __CallReducerFlags = 'FullUpdate';
  leaveMatchQueue(flags: __CallReducerFlags) {
    this.leaveMatchQueueFlags = flags;
  }

  rebuildLeaderboardFlags: __CallReducerFlags = 'FullUpdate';
  rebuildLeaderboard(flags: __CallReducerFlags) {
    this.rebuildLeaderboardFlags = flags;
  }

  recordContinuePaymentFlags: __CallReducerFlags = 'FullUpdate';
  recordContinuePayment(flags: __CallReducerFlags) {
    this.recordContinuePaymentFlags = flags;
  }

  registerPlayerFlags: __CallReducerFlags = 'FullUpdate';
  registerPlayer(flags: __CallReducerFlags) {
    this.registerPlayerFlags = flags;
  }

  setPlayerMusicFlags: __CallReducerFlags = 'FullUpdate';
  setPlayerMusic(flags: __CallReducerFlags) {
    this.setPlayerMusicFlags = flags;
  }

  startSingleRunFlags: __CallReducerFlags = 'FullUpdate';
  startSingleRun(flags: __CallReducerFlags) {
    this.startSingleRunFlags = flags;
  }

  updatePvpBoardFlags: __CallReducerFlags = 'FullUpdate';
  updatePvpBoard(flags: __CallReducerFlags) {
    this.updatePvpBoardFlags = flags;
  }

  updateSingleRunFlags: __CallReducerFlags = 'FullUpdate';
  updateSingleRun(flags: __CallReducerFlags) {
    this.updateSingleRunFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get gameRuns(): GameRunsTableHandle<'game_runs'> {
    // clientCache is a private property
    return new GameRunsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<GameRun>(REMOTE_MODULE.tables.game_runs));
  }

  get matchQueue(): MatchQueueTableHandle<'match_queue'> {
    // clientCache is a private property
    return new MatchQueueTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<MatchQueue>(REMOTE_MODULE.tables.match_queue));
  }

  get paymentRecords(): PaymentRecordsTableHandle<'payment_records'> {
    // clientCache is a private property
    return new PaymentRecordsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<PaymentRecord>(REMOTE_MODULE.tables.payment_records));
  }

  get players(): PlayersTableHandle<'players'> {
    // clientCache is a private property
    return new PlayersTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Player>(REMOTE_MODULE.tables.players));
  }

  get pvpLeaderboard(): PvpLeaderboardTableHandle<'pvp_leaderboard'> {
    // clientCache is a private property
    return new PvpLeaderboardTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<PvpLeaderboard>(REMOTE_MODULE.tables.pvp_leaderboard));
  }

  get pvpMatches(): PvpMatchesTableHandle<'pvp_matches'> {
    // clientCache is a private property
    return new PvpMatchesTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<PvpMatch>(REMOTE_MODULE.tables.pvp_matches));
  }

  get spLeaderboard(): SpLeaderboardTableHandle<'sp_leaderboard'> {
    // clientCache is a private property
    return new SpLeaderboardTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<SpLeaderboardEntry>(REMOTE_MODULE.tables.sp_leaderboard));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
