// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type Player = {
  wallet: string,
  totalGames: bigint,
  totalWins: bigint,
  pvpWins: bigint,
  musicOn: boolean,
  createdAt: __Timestamp,
  updatedAt: __Timestamp,
};
let _cached_Player_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const Player = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_Player_type_value) return _cached_Player_type_value;
    _cached_Player_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_Player_type_value.value.elements.push(
      { name: "wallet", algebraicType: __AlgebraicTypeValue.String },
      { name: "totalGames", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "totalWins", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "pvpWins", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "musicOn", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "createdAt", algebraicType: __AlgebraicTypeValue.createTimestampType() },
      { name: "updatedAt", algebraicType: __AlgebraicTypeValue.createTimestampType() },
    );
    return _cached_Player_type_value;
  },

  serialize(writer: __BinaryWriter, value: Player): void {
    __AlgebraicTypeValue.serializeValue(writer, Player.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Player {
    return __AlgebraicTypeValue.deserializeValue(reader, Player.getTypeScriptAlgebraicType());
  },

}

export default Player;


