// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { MatchType } from "./match_type_type";
// Mark import as potentially unused
declare type __keep_MatchType = MatchType;
import { MatchStatus } from "./match_status_type";
// Mark import as potentially unused
declare type __keep_MatchStatus = MatchStatus;


export type PvpMatch = {
  matchId: bigint,
  matchType: MatchType,
  player1Wallet: string,
  player2Wallet: string | undefined,
  status: MatchStatus,
  joinCode: string | undefined,
  player1Score: bigint,
  player2Score: bigint,
  player1BoardState: string,
  player2BoardState: string,
  matchDurationSeconds: bigint,
  winnerWallet: string | undefined,
  createdAt: __Timestamp,
  startedAt: __Timestamp | undefined,
  completedAt: __Timestamp | undefined,
  updatedAt: __Timestamp,
};
let _cached_PvpMatch_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const PvpMatch = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_PvpMatch_type_value) return _cached_PvpMatch_type_value;
    _cached_PvpMatch_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_PvpMatch_type_value.value.elements.push(
      { name: "matchId", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "matchType", algebraicType: MatchType.getTypeScriptAlgebraicType() },
      { name: "player1Wallet", algebraicType: __AlgebraicTypeValue.String },
      { name: "player2Wallet", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "status", algebraicType: MatchStatus.getTypeScriptAlgebraicType() },
      { name: "joinCode", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "player1Score", algebraicType: __AlgebraicTypeValue.I128 },
      { name: "player2Score", algebraicType: __AlgebraicTypeValue.I128 },
      { name: "player1BoardState", algebraicType: __AlgebraicTypeValue.String },
      { name: "player2BoardState", algebraicType: __AlgebraicTypeValue.String },
      { name: "matchDurationSeconds", algebraicType: __AlgebraicTypeValue.I64 },
      { name: "winnerWallet", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "createdAt", algebraicType: __AlgebraicTypeValue.createTimestampType() },
      { name: "startedAt", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.createTimestampType()) },
      { name: "completedAt", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.createTimestampType()) },
      { name: "updatedAt", algebraicType: __AlgebraicTypeValue.createTimestampType() },
    );
    return _cached_PvpMatch_type_value;
  },

  serialize(writer: __BinaryWriter, value: PvpMatch): void {
    __AlgebraicTypeValue.serializeValue(writer, PvpMatch.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): PvpMatch {
    return __AlgebraicTypeValue.deserializeValue(reader, PvpMatch.getTypeScriptAlgebraicType());
  },

}

export default PvpMatch;


